# Generated by Django 3.1.6 on 2021-03-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
